image: golang:1.11

stages:
  - test
  - coverage

before_script:
  - mkdir -p /go/src/gitlab.com
  - ln -s "/builds/$CI_PROJECT_NAMESPACE" "/go/src/gitlab.com/$CI_PROJECT_NAMESPACE"
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/vektra/mockery/.../

test:
  stage: test
  script:
    - cd /go/src/gitlab.com/$CI_PROJECT_PATH
    - make install
    - make test