env:
  global:
    - GO111MODULE=on

language: go
go:
  - 1.12.x
branches:
  only:
    - master
    - /^v-/
script:
  - go get -u github.com/golang/mock/gomock
  - go get -u github.com/golang/mock/mockgen
  - make install
  - make test